version: '3.8'
services:
    zabbix-agent:
        container_name: zabbix-agent
        image: zabbix/zabbix-agent
        environment:
            - ZBX_HOSTNAME=server1
            - ZBX_SERVER_HOST=zabbix-proxy
        ports:
          - "10050:10050/tcp"
    mariadb:
        container_name: mariadb:latest
        build:
            context: ../dockerfiles/zabbix-proxy/
            docker-file: Dockerfile
            image: mariadb:latest
        ports:
            - 3306:3306/tcp 
        volumes:
            - type: bind
              source: ../config/zabbix-proxy/schema.sql
              target: /docker-entrypoint-initdb.d/schema.sql
        environment:
            - MYSQL_ROOT_PASSWORD=zabbix

    zabbix-proxy:
        container_name: zabbix-proxy
        image: zabbix/zabbix-proxy-mysql
        ports:
            - 10051:10051/tcp 
        volumes:
            - type: volume
              source: snmp_zabbix-proxy_share
              target: "/etc/snmp/"
        environment:
            - MYSQL_ROOT_PASSWORD=zabbix
            - ZBX_PROXYMODE=0
            - ZBX_HOSTNAME=server1
            - BX_SERVER_HOST=192.168.10.22
            - ZBX_SERVER_PORT=10051
            - DB_SERVER_HOST=mariadb
            - DB_SERVER_PORT=3306
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=zabbix
#           - MYSQL_USER_FILE=
#           - MYSQL_PASSWORD_FILE=

volumes:
    snmp_zabbix-proxy_share:
        name: snmp_zabbix-proxy_share

